# Generated by Django 5.2.3 on 2025-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_default='', max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image1_about')),
                ('description', models.TextField(default='', max_length=600)),
                ('short_description1', models.TextField(db_default='', max_length=600)),
                ('title_headline1', models.CharField(db_default='', max_length=100)),
                ('title_headline2', models.CharField(db_default='', max_length=100)),
                ('title_headline3', models.CharField(db_default='', max_length=100)),
                ('short_description2', models.TextField(db_default='', max_length=600)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image2_about')),
                ('video', models.CharField(db_default='', max_length=100)),
            ],
        ),
    ]
