# Generated by Django 5.2.3 on 2025-06-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_service', models.CharField(db_default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=300)),
                ('speed', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
