# Generated by Django 5.2.3 on 2025-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_default='', max_length=100)),
                ('role_company', models.CharField(db_default='', max_length=100)),
                ('image', models.ImageField(upload_to='image_team')),
                ('url_x', models.CharField(default='', max_length=100)),
                ('url_facebook', models.CharField(default='', max_length=100)),
                ('url_instagram', models.CharField(default='', max_length=100)),
                ('url_linkedin', models.TextField(default='', max_length=100)),
                ('speed', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
