# Generated by Django 5.2.3 on 2025-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_default='', max_length=200)),
                ('reply', models.TextField(default='', max_length=1000)),
                ('speed', models.CharField(db_default='', max_length=100)),
            ],
        ),
    ]
