# Generated by Django 5.2.3 on 2025-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField()),
                ('date_message', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
